### PR TITLE
Remove placeholder and outdated documentation

### PR DESCRIPTION
**Pull request by bvhme**
Outdated and wrong documentation, never nice...

### CODE REVIEW

**Comment by bvhme** [comment]
With the extremely small amount of useful content in the 'Contributing' section of the Docs site, I would actually like to suggest removing that section and replacing it with a link to GitHub.
All of the content that is there now is also in the #193 version of the README.

I think it is worthwhile finding the best way to get developers using NLX to also become contributors, and for that, I think the best way is by taking them through the GitHub repository. So finding the right opportunities to send them there is valuable.

**Comment by bvhme** [comment]
In my view outdated or wrong documentation is just like technical debt, it is very hard to build upon and with. So when this gets merged I think it opens up a lot of space for documentation work to be done.

**Comment by ehotting** [comment]
Oh, you cannot merge now? :)

**Comment by bvhme** [comment]
Nope, I'm not 'authorized'

Which is fine, but then you should merge :)

screen shot 2018-05-21 at 09 12 28

**Pull request merged**
